# Workflow for building and deploying a React app to GitHub Pages
name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ✅ Use npm install instead of npm ci to avoid missing lockfile error
      - name: Install dependencies
        run: npm install

      # 🔧 Build your React app
      - name: Build React app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # ✅ Upload only the build folder (where React outputs index.html, CSS, JS)
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
